### ISSUE TITLE
Call to undefined method Metaregistrar\\EPP\\sidnEppResponse::getContactId()

### ISSUE THREAD

**Issue by kevinvdburgt** [metaregistrar/php-epp-client#120]
When trying to create a contact using SIDN I've got the following exception:
`Call to undefined method Metaregistrar\\EPP\\sidnEppResponse::getContactId()`

While using the following code:

```php
try {
    $contact = new sidnEppCreateContactRequest($contactInfo);
    if ($response = $this->connection->request($contact)) {
        return $response->getContactId();
    }
} catch (eppException $exception) {
    throw new DomainException($exception->getMessage());
}
```

**Comment by metaregistrar** [comment]
Yes, i noticed this problem also in the last week - i have fixed it in the latest version.

In sidn-ext-epp-1.0/includes.php there should be this line:
$this->addCommandResponse('Metaregistrar\EPP\sidnEppCreateContactRequest', 'Metaregistrar\EPP\eppCreateContactResponse');

This connects sidnEppCreateContactRequest to eppCreateContactResponse instead of sidnEppResponse, which was not correct.

**Comment by kevinvdburgt** [comment]
Where can I find the last version :) ?

**Comment by metaregistrar** [comment]
Just download it again from Github

**Comment by kevinvdburgt** [comment]
Thanks, this issue can be closed :)
