### ISSUE TITLE
Fetch nameserver groups

### ISSUE THREAD

**Issue by bibawa** [metaregistrar/php-epp-client#146]
Hi,

We've domains in our DNS.BE portfolio with a nameservergroup configured..If we fetch the information about the domain with the infodomain.php example scripts there are no nameservers listed and there's also no reference set to the nameservergroup..

How can we handle domains with nameserversgroups? How can we see which nameservergroup is assigned to the domain and after that which nameservers are assigned to that group ? 

Thanks you!

**Comment by metaregistrar** [comment]
Hello,

This was missing from the dnsbeEppInfoDomainResponse, i have added it now. You can request an info domain to see if there is a nameserver group attached, however, i have not added the code to retrieve the info on the nameserver group itself, because we do not use nameserver groups so it is a lot of work to test it.
