### ISSUE TITLE
Error 2102: Unimplemented option (Contact password is not supported)

### ISSUE THREAD

**Issue by doppiej** [metaregistrar/php-epp-client#15]
I changed the file 'createcontact.php' in the 'Examples' folder.
I changed the following line to change it to openprovider:
$conn = new Metaregistrar\EPP\openproviderEppConnection();

The error I get is:
Error 2102: Unimplemented option (Contact password is not supported)

How is this possible?

**Comment by metaregistrar** [comment]
In my eppCreateContactRequest code, i set a standard password of foo2bar for each created contact, which now (upon reflection) seems really stupid.

I have changed the code so the password is only set when it is specified on the contact object, you should have no trouble any more. Please pull the latest version for this.

Please note that some registries require a password. So for OpenProvider, you should remove the line "$contactinfo->setPassword('');", otherwise a blank password is still sent with each create contact request.

**Comment by doppiej** [comment]
I updated my files, but I can't locate the $contactinfo->setPassword(''); in your files.
I am using this to create a contact. I never specify the password, but it still gives the same error...

```function createcontact($conn,$email,$telephone,$name,$organization,$address,$postcode,$city, $country)
{
    try
    {
        $postalinfo = new Metaregistrar\EPP\eppContactPostalInfo($name, $city, $country, $organization, $address, null, $postcode, Metaregistrar\EPP\eppContactPostalInfo::POSTAL_TYPE_INTERNATIONAL);
        $contactinfo = new Metaregistrar\EPP\eppContact($postalinfo, $email, $telephone);
		echo "<pre>".print_r($contactinfo,true)."</pre>";
        $contact = new Metaregistrar\EPP\eppCreateContactRequest($contactinfo);
        if ((($response = $conn->writeandread($contact)) instanceof Metaregistrar\EPP\eppCreateResponse) && ($response->Success()))
        {
            echo "Contact created on ".$response->getContactCreateDate()." with id ".$response->getContactId()."\n";
            return $response->getContactId();
        }
    }
    catch (Metaregistrar\EPP\eppException $e)
    {
        echo $e->getMessage()."\n";
    }
    return null;
}```
