### ISSUE TITLE
How to register a .fr domain with rrpproxy

### ISSUE THREAD

**Issue by BrainFeeder** [metaregistrar/php-epp-client#160]
Hello

As they show on the rrpproxy wiki page, I know that a registration of a .fr domain needs extra parameters.
Is this possible with the epp-client? I get a 'command syntax' error.

[RRP Wiki](https://wiki.rrpproxy.net/domains/tlds/fr)

**Comment by metaregistrar** [comment]
Hi Robrecht,

php-epp-client contains a basic implementation for RRPPROXY, however not
all extensions for all TLDs that RRPPROXY manages have been implemented.

In this case you would have to modify the extension yourself to add the
code for the extra parameters that .FR requires.

However, please note: Afnic does not require these extra fields any more
for .FR registrations since 2016. So if RRPPROXY still needs them, you need
to contact their support desk and ask if they can modify their
implementation for .FR



Vriendelijke groeten/kind regards,

Ewout de Graaf
Metaregistrar BV


Op do 20 sep. 2018 om 11:16 schreef Robrecht Wellens <
notifications@github.com>:

**Comment by BrainFeeder** [comment]
Thank you for fast reply! I'll check on those requirements again. 

Do you have an idea of which extensions can result in problems?

**Comment by BrainFeeder** [comment]
Hence the reason why I was happy to find this repo :D 
Well, guess we'll have to reshedule our deadline :p

**Comment by metaregistrar** [comment]
You can also join a registrar with real good support that will take most of the hassle away from you ;-)

https://www.metaregistrar.com

**Comment by BrainFeeder** [comment]
:D Yeah, I've mentioned it believe me... Thing is, our company exists a long time and they seem to be afraid of changes. Like I'm rebuilding their control system now, but they want it to look,work,act,.. the same as the old one does... Why am I even doing this project -- lol.  If I ask for feedback on some fancy form or table they'll be like "*sigh* doesn't matter, just finish it". 

Sorry for spitting out my frustrations of a friday morning in here :D 

Any way, I'll try to automate a test somehow to see if there are any extensions that cause problems.
We don't support a huge amount of TLDs so I might be lucky :p

**Comment by metaregistrar** [comment]
Good luck - and don't hesitate to ask if you run into problems. We do have a lot of experience in domain names, and also with connections to key-systems ;-)

**Comment by BrainFeeder** [comment]
I'll keep that in mind :)
