### ISSUE TITLE
authinfo field should be a cdata ?

### ISSUE THREAD

**Issue by f4810** [metaregistrar/php-epp-client#231]
Hi, 
I'm having trouble to send this authinfo: `&&6LD"6s`
There is not way to get a valid XML. 
What can I do?

**Comment by metaregistrar** [comment]
Hello,

I checked and found that the login section already used CDATA for passwords, but the domain:create, domain:info and domain:update parts did not. I have now updated the code so that the domain functions also use CDATA sections for their passwords. By default, the use of CDATA is ON, but if a registry does not support it, you can switch it off with an eppRequest->setUseCdata(false);

**Comment by michael-gilch** [comment]
Hi, 
Can the useCdata() switch also be implemented for domain:transfer? Class eppTransferRequest uses hard-coded CDATA sections for transfer requests. However, all the other transfer operations (e.g. query) don't use CDATAs at all.

**Comment by metaregistrar** [comment]
Haha, your are right. The CDATA option was added to the login request when I encountered a registry with a password that contained < and > characters.

The CDATA option now also has been added to the eppTransferRequest and metaregEppTransferRequest
