### ISSUE TITLE
API

### ISSUE THREAD

**Issue by homeforce** [metaregistrar/php-epp-client#236]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**
Is there a possibility to add an api on your php layer? 
Or do you have a crud api available? 

* **What is the motivation / use case for changing the behavior?**
So we can automate domain registrations.

**Comment by metaregistrar** [comment]
It is not easy to create a simple API that would automate this PHP layer. The problem is that it connects to many different registries, and all registries have different connection and EPP requirements. That is exactly why there is so much need for a good PHP implementation, because there is much variety in registry connections worldwide. The flexibility of this PHP implementation is not easily translated into a CRUD or REST API.
