### ISSUE TITLE
about eppCheckResponse.php

### ISSUE THREAD

**Issue by jansen-s** [metaregistrar/php-epp-client#255]
I found that all methods in the eppCheckResponse.php class already contain the methods in the class eppCheckDomainResponse / eppCheckHostResponse / eppCheckContactResponse, except for a few code differences, all are the same, so there is no need to keep these three classes.

**Comment by metaregistrar** [comment]
You are right, the eppCheckResponse.php is the oldest one, and was later replaced by eppCheckDomainResponse.php because that was a clearer name. The old eppCheckResponse.php was only maintained because *maybe* someone was still using it. If i just remove it and someone still uses the command, then the code breaks, and that is not what we aspire.
