### ISSUE TITLE
I cant make a Domain Transfer to DNS Belgium working

### ISSUE THREAD

**Issue by sayoki** [metaregistrar/php-epp-client#265]
The only response I receive = Error 2004: Parameter value range error

Did someone get this working?

**Comment by metaregistrar** [comment]
When creating the transfer, do you create an eppTransferRequest, or do you create a dnsbeEppTransferRequest?

Because a normal eppTransferRequest does not contain the fields that DNSBE requires.

**Comment by sayoki** [comment]
I tried both.

Class 'dnsbeEppTransferRequest' not found

I did add the following code before connecting:
$conn->useExtension("dnsbe-1.0");

**Comment by metaregistrar** [comment]
The dnsbeEppTransferRequest takes more parameters than just the standard domain and operation parameters. 

```
function __construct($operation, $object, $tech = null, $billing = null, $onsite = null, $registrant = null) {
```
You need to specify tech, billing, onsite and registrant parameters before issuing the request. That is why there is a different request from the standard one.

Because these parameters are missing, DNS Belgium is not accepting your transfer.

**Comment by sayoki** [comment]
These values are already known in the $object.

Adding them again as parameters gives me the following error message:
Error 2303: Object does not exist
