### ISSUE TITLE
Need help in 'HostName Create / Update' or 'ChildHost Name' Services API.

### ISSUE THREAD

**Issue by nullcall** [metaregistrar/php-epp-client#28]
I have not found anything which can create / update Name Servers for Domain Name. Kindly help me.
plz for snapshot got through below or help me for logic so i can build the same. If you need i can share whole logic docs.

For example:

1.   CHECK is executed for ns.example.com and returns “1000 success” 
2.	CHECK is executed for example.com (the parent domain):
a.	If example.com does not exist, the system returns an error code and example.com must be added prior to adding the host.
b.	If example.com does exist, then the CREATE command for ns.example.com can be executed.
 
•	VeriSign Naming Services allows use of hosts registered in other TLDs, such as ccTLDs, referred to as “external hosts”.  For example, a host named ns1.example.com.au can be used to provide service for the domain example.com.  Such hosts must be registered with the VeriSign Registry before they can be used, but an IP address is NOT allowed. VeriSign Com/Net Registry will not accept IP addresses for hosts that are outside of the Com or Net TLD (e.g. ns1.example.ca). The authoritative registry for the non Com or Net host will resolve the IP Address in their zone file.

**Comment by metaregistrar** [comment]
The process of changing a nameserver can be very confusing, because some registries use the HostAttr parameters to set nameservers, and some registries use the HostObj parameters.

Basically, when a registry uses HostAttr, you can just change nameservers on a domain name, no prerequisites needed.

When a registry uses HostObj, the registry will require you to create a host object for this nameserver (if it does not exist) first. You can check the existence of a nameserver (host object) with the host:check command.

Since you are referring to Verisign, which uses HostObjects, i will presume this is the way to go for you.

I have just added 2 Example files for you, Examples/checkhost.php and Examples/createhost.php how to check or create host objects.

Please review Examples/modifydomain.php on how to modify a domain name with new nameserver information.

**Comment by nullcall** [comment]
Thanx for reply. I'll do the same if any issue then let you know.
