### ISSUE TITLE
Verisign SRS fully supported?

### ISSUE THREAD

**Issue by tespio** [metaregistrar/php-epp-client#282]
Hi,

Does the metaregistrar class fully supports the Verisign SRS for .com/.net? I saw the extension for verisign in the extensions directory but i just wanted to make sure it implements all their functionality. Thank you in advance for clarifications.

**Comment by metaregistrar** [comment]
Hi,

This php-epp-client repository relies heavily on the contributions of users using the repository and adding functionality. So the verisign connection has been added by a user of this repository, but since I have not used it myself, I cannot really tell if it covers all the functionality or not. Please review the code to see which functions are covered.

**Comment by tespio** [comment]
Thank you. I will take a look and see.
