### ISSUE TITLE
can this support .in registry 

### ISSUE THREAD

**Issue by todaysprint** [metaregistrar/php-epp-client#383]
Checking 1 domain names ==== LOG ==== -----ERROR-----2024-05-09 05:00:42----- Connection could not be opened: 0 -----END-----2024-05-09 05:00:42-----

**Comment by metaregistrar** [comment]
If the registry supports EPP, then php-epp-client can support it.

The fact that you cannot open a connection is probably due to either:
1. You have not whitelisted your IP adresses at the registry or
2. You have not opened the correct outgoing port(s) on your server.
These are the most common problems that we see with connection errors.
