### ISSUE TITLE
domain:authInfo element created even if the auth_code is not being provided

### ISSUE THREAD

**Issue by marcuan** [metaregistrar/php-epp-client#67]
For the eppInfoDomainRequest, the domain:authInfo element is being created even if the auth_code is not provided, this is because in the eppDomain object the authorisation_code is initialized with an empty string value so it avoids the is_null verification used in the eppInfoDomainRequest.

**Comment by marcuan** [comment]
It's a really easy fix, just change the line 68 of the Protocols\EPP\eppData\eppDomain.php and instead of:

```
    private $authorisationCode = '';
```
use:
```
    private $authorisationCode = null;
```

**Comment by metaregistrar** [comment]
The fix is easy, but i have to test it using our test suites. So far i have seen 3 types of behaviour from the registries:
1 - Some don't want the authcode field at all
2 - Some don't use it, but it must be there otherwise you receive an error
3 - Some use it

The RFC states the AuthInfo field is OPTIONAL, so i will test the fix to set it to null.
