### ISSUE TITLE
Domain transfer error

### ISSUE THREAD

**Issue by MrKoopie** [metaregistrar/php-epp-client#92]
First of all, thanks for the great module. It makes connecting to EPP much easier.

I did find an error in the code of transferdomain.php. When I try to transfer a domain in a test environment, I get the following error:

"Error 2003: Required parameter missing; The command-ext-domain-1.0:transfer element is missing."

I did replace eppConnection with metaregEppConnection. I have even tried to replace eppTransferRequest with \Metaregistrar\EPP\metaregEppTransferExtendedRequest, however this gives the following error:
"eppDomain object has no registrant on metaregEppTransferExtendedRequest"

When I add the contact:
"Empty XML document when receiving data!"

When I add the contacts and nameservers:
"Empty XML document when receiving data!"

Before I had replaced eppTransferRequest, I assumed that the client would take care of using the correct Request classes. Any idea how this can be resolved?

**Comment by metaregistrar** [comment]
Hi,

First of all, which registry are you connecting to for these transfers?

If you are connecting to our services (eppltest.metaregistrar.com) then you should be using metaregEppConnection and metaregEppTransferExtendedRequest. 

If you are trying this with another registry, then you will probably have to use the eppTransferRequest.

A transfer request may take some while (even up to 5-10 seconds). So please make sure your time-outs are long enough, otherwise you will receive empty XML returns on your transfers.

**Comment by MrKoopie** [comment]
@metaregistrar I am using Metaregistrar (you guys) for this.

Regarding the timeout: it takes way more than 10 seconds (probably a minute, I did not time it). Everything is in the test environment and I have registered a domain with a second registrar in the SIDN test environment which should be transferred to you. Should I increase the timeout?

**Comment by metaregistrar** [comment]
A transfer that takes a minute is not okay - increasing the timeouts will not help here, i'm afraid.

Please send the domain you are trying to transfer to support@metaregistrar.com, and we'll find out what went wrong.

**Comment by MrKoopie** [comment]
I have send an e-mail and will close this issue. Thanks!
